AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

# TODO: Re-enable me when upgrading from Rubocop 0.49.0 - there is a bug in this version,
# fixed by https://github.com/bbatsov/rubocop/issues/4412, which causes it to be broken
# when the condition has literals on both sides, as in sidekiq_web.ru
Style/YodaCondition:
  Enabled: false
