AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - bin/**/*

Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
